### ISSUE TITLE
Make a decision on license to use

### ISSUE THREAD

**Issue by rjnienaber** [vvcb/PatManPlus#10]
There was a brief discussion about the differences between [MIT](https://en.wikipedia.org/wiki/MIT_License), [GPL](https://en.wikipedia.org/wiki/GNU_General_Public_License) and [LGPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License). It would be good to come to a decision and update [the license field](https://github.com/vvcb/PatManPlus/blob/d753e2847864ebceae2a2dfe5c6956492e8a4e24/package.json#L8) if need be.

**Comment by vvcb** [comment]
Looking at this now - https://choosealicense.com/licenses/

Will have a little think over the next 24 hours regarding whether we put this in a restrictive copyleft such as AGPL3 or a permissive MIT license. Welcome everyone's views on this on Slack.

**Comment by rjnienaber** [comment]
Changes committed and issue close based on our conversation.
