### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by rjnienaber** [vvcb/PatManPlus#11]
[Travis CI](https://travis-ci.org/) is a great way to perform [continuous integration](https://en.wikipedia.org/wiki/Continuous_integration) and is free for open source projects. We can use it to run the unit tests on feature branches and pull requests to ensure that they pass before merging in.

**Comment by vvcb** [comment]
Travis CI now has access to the repo. Someone intelligent @rjnienaber / @okouam  will have to look at https://docs.travis-ci.com/user/languages/javascript-with-nodejs/. I will leave this issue as open until you are happy that the integration is complete and Travis is building the application correctly.

**Comment by rjnienaber** [comment]
This has been fixed now with 78e641979d16a76728827270ad75007e3b298d13
