### ISSUE TITLE
Add description for project

### ISSUE THREAD

**Issue by rjnienaber** [vvcb/PatManPlus#13]
It would be good to provide a top level description on the landing page of GitHub. Here's a brief example idea:

_Allows junior doctors to manage their patient lists to provide an efficient way to complete a ward round_

**Comment by vvcb** [comment]
Next-Gen Patient Lists for Junior Doctors - This will change the life of every junior doctor in the NHS and beyond! https://vvcb.github.io/PatManPlus/
