### ISSUE TITLE
Integrate GitHub events into Slack

### ISSUE THREAD

**Issue by rjnienaber** [vvcb/PatManPlus#19]
It would be good to see a timeline of changes (Pull Requests, New Issues, Commits, Comments, etc.) in a chronological way so that it's easy to catch up on any changes. The integration should be relatively straightforward and I propose that it goes to a '#github' channel.

Here's the link: [Slack Integration](https://github.com/integrations/slack)

The integration process starts with the 'Learn More' button.

**Comment by vvcb** [comment]
Integrated into #github-integration on slack
