### ISSUE TITLE
Ability to view/change database location

### ISSUE THREAD

**Issue by vvcb** [vvcb/PatManPlus#27]
- The initial file picker for the database should allow selection of only one particular file extension - it is not clear what this is. The application should have its own file extension (like some_file_name.patman) or a more generic file extension. The database picker must limit any selection to this extension.

- Once a database has been chosen, it should be possible to see this either in the title bar of the app or within the UI.

- It should also test that it is a valid SQLite database file (i.e. it should try and connect to it)

- It should be possible to pick a different database from File...Open Patient List.

**Comment by vvcb** [comment]
I have marked this as a bug as I am stuck with an empty app after choosing the wrong settings file. I guess once it is fixed it will be a very useful enhancement.

**Comment by rjnienaber** [comment]
> It should be possible to pick a different database from File...Open Patient List.

I plan to add this as part of #22.

> I am stuck with an empty app after choosing the wrong settings file.

If you delete the settings file it should ask you to choose again on startup. The current location of the settings file should be listed in the output of the terminal/console screen.

**Comment by vvcb** [comment]
The settings file is located at app/backend/settings.js according to console. 

![image](https://cloud.githubusercontent.com/assets/8311806/22879331/6e924910-f1d5-11e6-9b5d-8ae9616eab3c.png)

When i delete this, the app complains regarding this being a missing module.

![image](https://cloud.githubusercontent.com/assets/8311806/22879363/991cebc2-f1d5-11e6-9d63-ab720d48db71.png)

And...i am still getting the sqlite error..grrr....!!!

**Comment by vvcb** [comment]
My bad...it is settings.conf
Ignore previous comment

**Comment by rjnienaber** [comment]
So I've just gone with the generic file extension `.sqlite3` and you can see the location by going opening the settings dialog (`Ctrl + S`). Let me know if there's anything that should be changed.
