### ISSUE TITLE
Create an onclick event for 'Cancel' button in patient list

### ISSUE THREAD

**Issue by vvcb** [vvcb/PatManPlus#29]
The cancel button (deliberately made small and showing an icon) should revert any changes that have been made to the record and reload the specific record from the database. 

This serves two purposes:
1. Undo changes made
2. Update the UI with latest data from the database

**Comment by rjnienaber** [comment]
Can I suggest that it be called `Reload` rather than `Cancel` ? I think it might be strange for a user to click `Cancel` if he wanted to see the latest data.
