### ISSUE TITLE
Ward DIsplay

### ISSUE THREAD

**Issue by CarolineMorton** [vvcb/PatManPlus#5]
On the long list of patients when they are unfiltered,  you cannot see the ward that the patient is on. Is it blank.

**Comment by okouam** [comment]
The reason for this is because the patients are not in wards contained in our wards.json file (the list of available wards). So we'll have to update our wards.json file to match the ones in our patient demos.

**Comment by rjnienaber** [comment]
This has been tightened up  by storing the ward information in the database. Let me know if this should be reopened.
