### ISSUE TITLE
Context predictive text completion

### ISSUE THREAD

**Issue by llogostevo** [vvcb/PatManPlus#8]
A method for predictive text in the long answer fields 

Similar to google predictive text the method would allow suggestions as fields in long answer sections are completed.

**Comment by vvcb** [comment]
https://ace.c9.io/ seems to be the right tool for this.  For some future date before we grey. @okouam @rjnienaber Maybe this will be a focussed hack for the London event.

**Comment by rjnienaber** [comment]
@vvcb, I could be mistaken but I believe the described functionality is more commonly known as `autocomplete` and is generally quite lightweight. Here's [an example using jquery](https://jqueryui.com/autocomplete/#categories). I believe Ace is a client side text editor providing support for programming languages akin to Sublime.

Is something like that more in line with what's required?

**Comment by rjnienaber** [comment]
![image](https://cloud.githubusercontent.com/assets/521795/22630891/edefabe4-ebf9-11e6-9d25-64f3c20e25bc.png)

Some more context:

> ...a lot of medical text is repetitive and predictable. I think it should be possible to give some structure to text entry. 

> Say someone typing in pn.. gets options of pneumonia as well as pneumonia variants showing up. 

Example: Jobs section

>Typing in []CT brings up CT chest, CT abdomen, etc.. the order being learnt from previous usage

(Note that the '[]' refers to a markdown like syntax that would render a checkbox in a text box and would be implemented in #2)
